### PR TITLE
add app-secrets samples

### PR DESCRIPTION
**Pull request by tsubakimoto**
I fixed it because I didn't see the sample in the app secret document.
The URL of the document is here.
https://docs.microsoft.com/ja-jp/aspnet/core/security/app-secrets

2018-06-06_20h26_53

The sample is used here.
https://github.com/aspnet/Docs/tree/master/aspnetcore/security/app-secrets/samples

### CODE REVIEW

**Comment by v-radelg** [comment]
Hello @tsubakimoto  , thank for your contribution. We are currently reviewing it. 

We will communicate the decision taken accordingly. Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by tsubakimoto** [comment]
Hello @v-radelg .
What is the status of this PR?
Is there anything I can do to help?

**Comment by v-radelg** [comment]
Hello @tsubakimoto , We are still reviewing it.

We will communicate the decision taken accordingly. Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Comment by tsubakimoto** [comment]
Hello @v-radelg
When will the review end?

**Comment by v-radelg** [comment]
Hi @tsubakimoto 
We are still working on your suggestions, please bear with us while we complete the process. It could take a few more weeks. We will keep you posted

Thank you for your effort and patience

Kind regards, Microsoft C&E Localization Team

**Comment by v-radelg** [comment]
@tsubakimoto , thank you for your feedback and suggestion! 
		
The writer considered the current version is correct and does not require the modifications suggested. 

>"We're not adding code names to the links. We actually went to the trouble to remove all of them because:
They have no impact on rendered docs.
They were mostly wrong (i.e., "Main").
They're too difficult to maintain."

We are closing this PR.

Thanks for your time and support.  

Kind regards,  Microsoft C&E Localization Team

**Comment by tsubakimoto** [comment]
@v-radelg What was the problem with my PR? It is understood that it is closed without explanation.
Branch problem? Or is it a sample code issue?

**Comment by v-radelg** [comment]
Hi @tsubakimoto 

According to the writer, they purposely removed the names from the link. This was escalated here https://github.com/aspnet/Docs/pull/6921

Thanks for your time and support.

Kind regards, Microsoft C&E Localization Team

**Pull request closed without merging**
