### PR TITLE
translate readme.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by beachside-project**
Translate readme.md.
Add CONTRIBUTING.md and translate it.

### CODE REVIEW

**Comment by v-jacard** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **Line 16**: **[Error]** Restore nuget package W:\dcpp-s\.optemp\CRR\_themes.pdf\packages.config in folder:W:\dcpp-s\.optemp\CRR\_themes.pdf failed, possibly due to transient errors from nuget servers. Please retry building your content again. If the issue still happens, open a ticket in http://MSDNHelp. Detailed error: Unable to find version &#39;1.28.0-alpha-107-g39c19d1&#39; of package &#39;opbuild.templates.common&#39;.

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C4%5C14%5C92eaaecd-9596-bf41-1e68-c50657be3c29%5CPullRequest%5C201704140621291909-1%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by beachside-project** [comment]
Should I Submit  a another PR again?

**Comment by gosali** [comment]
Hi @beachside-project , we are still in discussing, will update the decision later soon. 
  
Thanks for your support,
Microsoft C&E Localization Team

**Comment by gosali** [comment]
@beachside-project: Thank you for your feedback and suggestion! 
  
The feedback is considered. We will tune part of  your feedbacks in order to comply with Microsoft Style Guide, then release this article in the next loc release round.
  
Microsoft C&E Localization Team

**Pull request merged**
